// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/about/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/about">> = Specific
  const handler = {} as typeof import("../../app/about/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/emails/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/emails">> = Specific
  const handler = {} as typeof import("../../app/admin/emails/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/analytics/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/analytics">> = Specific
  const handler = {} as typeof import("../../app/analytics/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/badges/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/badges">> = Specific
  const handler = {} as typeof import("../../app/badges/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/builder/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/builder">> = Specific
  const handler = {} as typeof import("../../app/builder/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dashboard/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dashboard">> = Specific
  const handler = {} as typeof import("../../app/dashboard/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev/[slug]">> = Specific
  const handler = {} as typeof import("../../app/dev/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/dev/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/dev">> = Specific
  const handler = {} as typeof import("../../app/dev/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leikir/arnor-clicker/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leikir/arnor-clicker">> = Specific
  const handler = {} as typeof import("../../app/leikir/arnor-clicker/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leikir/heidursordla/[puzzleId]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leikir/heidursordla/[puzzleId]">> = Specific
  const handler = {} as typeof import("../../app/leikir/heidursordla/[puzzleId]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leikir/heidursordla/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leikir/heidursordla">> = Specific
  const handler = {} as typeof import("../../app/leikir/heidursordla/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leikir/horpuhopp/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leikir/horpuhopp">> = Specific
  const handler = {} as typeof import("../../app/leikir/horpuhopp/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/leikir/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/leikir">> = Specific
  const handler = {} as typeof import("../../app/leikir/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/palette/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/palette">> = Specific
  const handler = {} as typeof import("../../app/palette/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/profile/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/profile">> = Specific
  const handler = {} as typeof import("../../app/profile/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/programs/[id]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/[id]">> = Specific
  const handler = {} as typeof import("../../app/programs/[id]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/programs/favorites/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs/favorites">> = Specific
  const handler = {} as typeof import("../../app/programs/favorites/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/programs/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/programs">> = Specific
  const handler = {} as typeof import("../../app/programs/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/settings/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/settings">> = Specific
  const handler = {} as typeof import("../../app/settings/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/social/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/social">> = Specific
  const handler = {} as typeof import("../../app/social/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/tags/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/tags">> = Specific
  const handler = {} as typeof import("../../app/tags/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/unsubscribe/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/unsubscribe/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/[auth0]/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/[auth0]">> = Specific
  const handler = {} as typeof import("../../app/api/auth/[auth0]/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/auth/token/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/auth/token">> = Specific
  const handler = {} as typeof import("../../app/api/auth/token/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/config/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/config">> = Specific
  const handler = {} as typeof import("../../app/api/config/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/contributors/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/contributors">> = Specific
  const handler = {} as typeof import("../../app/api/contributors/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/devlogs/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/devlogs">> = Specific
  const handler = {} as typeof import("../../app/api/devlogs/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/emails/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails">> = Specific
  const handler = {} as typeof import("../../app/api/emails/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/emails/unsubscribe/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/emails/unsubscribe">> = Specific
  const handler = {} as typeof import("../../app/api/emails/unsubscribe/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/leikir/[game]/scores/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/leikir/[game]/scores">> = Specific
  const handler = {} as typeof import("../../app/api/leikir/[game]/scores/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/programs/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/programs">> = Specific
  const handler = {} as typeof import("../../app/programs/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
