"""add emaillist table

Revision ID: ceb879a8a258
Revises: d6dda80d43b1
Create Date: 2025-11-08 14:14:17.269283

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ceb879a8a258"
down_revision: Union[str, Sequence[str], None] = "d6dda80d43b1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "emaillist",
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.PrimaryKeyConstraint("email"),
        sa.UniqueConstraint("email", name="uq_emaillist_email"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("emaillist")
    # ### end Alembic commands ###
